version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: fsdtracker
      POSTGRES_PASSWORD: fsdtracker
    ports:
      - '10001:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: ghcr.io/jendib/fsdtracker/api:latest
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://fsdtracker_db_1/fsdtracker'
      QUARKUS_DATASOURCE_USERNAME: 'fsdtracker'
      QUARKUS_DATASOURCE_PASSWORD: 'fsdtracker'
    ports:
      - '10002:8080'

  web:
    image: ghcr.io/jendib/fsdtracker/web:latest
    restart: always
    ports:
      - '10003:80'

volumes:
  db:
