name: build

on:
  push:
    branches:
      - master
permissions:
  packages: write
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - working-directory: api
        run: mvn clean package
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: api
          tags: ghcr.io/jendib/fsdtracker/api:latest
          file: api/src/main/docker/Dockerfile.jvm
          push: true
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: web
          tags: ghcr.io/jendib/fsdtracker/web:latest
          file: web/Dockerfile
          push: true